/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class neoevent_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected neoevent_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(neoevent_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        icsneojavaJNI.delete_neoevent_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDescription(String value) {
    icsneojavaJNI.neoevent_t_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return icsneojavaJNI.neoevent_t_description_get(swigCPtr, this);
  }

  public void setTimestamp(SWIGTYPE_p_time_t value) {
    icsneojavaJNI.neoevent_t_timestamp_set(swigCPtr, this, SWIGTYPE_p_time_t.getCPtr(value));
  }

  public SWIGTYPE_p_time_t getTimestamp() {
    return new SWIGTYPE_p_time_t(icsneojavaJNI.neoevent_t_timestamp_get(swigCPtr, this), true);
  }

  public void setEventNumber(long value) {
    icsneojavaJNI.neoevent_t_eventNumber_set(swigCPtr, this, value);
  }

  public long getEventNumber() {
    return icsneojavaJNI.neoevent_t_eventNumber_get(swigCPtr, this);
  }

  public void setSeverity(short value) {
    icsneojavaJNI.neoevent_t_severity_set(swigCPtr, this, value);
  }

  public short getSeverity() {
    return icsneojavaJNI.neoevent_t_severity_get(swigCPtr, this);
  }

  public void setSerial(String value) {
    icsneojavaJNI.neoevent_t_serial_set(swigCPtr, this, value);
  }

  public String getSerial() {
    return icsneojavaJNI.neoevent_t_serial_get(swigCPtr, this);
  }

  public void setReserved(short[] value) {
    icsneojavaJNI.neoevent_t_reserved_set(swigCPtr, this, value);
  }

  public short[] getReserved() {
    return icsneojavaJNI.neoevent_t_reserved_get(swigCPtr, this);
  }

  public neoevent_t() {
    this(icsneojavaJNI.new_neoevent_t(), true);
  }

}
