/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class neomessage_statusbitfield_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected neomessage_statusbitfield_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(neomessage_statusbitfield_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        icsneojavaJNI.delete_neomessage_statusbitfield_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGlobalError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_globalError_set(swigCPtr, this, value);
  }

  public long getGlobalError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_globalError_get(swigCPtr, this);
  }

  public void setTransmitMessage(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_transmitMessage_set(swigCPtr, this, value);
  }

  public long getTransmitMessage() {
    return icsneojavaJNI.neomessage_statusbitfield_t_transmitMessage_get(swigCPtr, this);
  }

  public void setExtendedFrame(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_extendedFrame_set(swigCPtr, this, value);
  }

  public long getExtendedFrame() {
    return icsneojavaJNI.neomessage_statusbitfield_t_extendedFrame_get(swigCPtr, this);
  }

  public void setRemoteFrame(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_remoteFrame_set(swigCPtr, this, value);
  }

  public long getRemoteFrame() {
    return icsneojavaJNI.neomessage_statusbitfield_t_remoteFrame_get(swigCPtr, this);
  }

  public void setCrcError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_crcError_set(swigCPtr, this, value);
  }

  public long getCrcError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_crcError_get(swigCPtr, this);
  }

  public void setCanErrorPassive(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canErrorPassive_set(swigCPtr, this, value);
  }

  public long getCanErrorPassive() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canErrorPassive_get(swigCPtr, this);
  }

  public void setIncompleteFrame(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_incompleteFrame_set(swigCPtr, this, value);
  }

  public long getIncompleteFrame() {
    return icsneojavaJNI.neomessage_statusbitfield_t_incompleteFrame_get(swigCPtr, this);
  }

  public void setLostArbitration(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_lostArbitration_set(swigCPtr, this, value);
  }

  public long getLostArbitration() {
    return icsneojavaJNI.neomessage_statusbitfield_t_lostArbitration_get(swigCPtr, this);
  }

  public void setUndefinedError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_undefinedError_set(swigCPtr, this, value);
  }

  public long getUndefinedError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_undefinedError_get(swigCPtr, this);
  }

  public void setCanBusOff(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canBusOff_set(swigCPtr, this, value);
  }

  public long getCanBusOff() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canBusOff_get(swigCPtr, this);
  }

  public void setCanErrorWarning(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canErrorWarning_set(swigCPtr, this, value);
  }

  public long getCanErrorWarning() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canErrorWarning_get(swigCPtr, this);
  }

  public void setCanBusShortedPlus(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canBusShortedPlus_set(swigCPtr, this, value);
  }

  public long getCanBusShortedPlus() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canBusShortedPlus_get(swigCPtr, this);
  }

  public void setCanBusShortedGround(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canBusShortedGround_set(swigCPtr, this, value);
  }

  public long getCanBusShortedGround() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canBusShortedGround_get(swigCPtr, this);
  }

  public void setChecksumError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_checksumError_set(swigCPtr, this, value);
  }

  public long getChecksumError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_checksumError_get(swigCPtr, this);
  }

  public void setBadMessageBitTimeError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_badMessageBitTimeError_set(swigCPtr, this, value);
  }

  public long getBadMessageBitTimeError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_badMessageBitTimeError_get(swigCPtr, this);
  }

  public void setIfrData(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_ifrData_set(swigCPtr, this, value);
  }

  public long getIfrData() {
    return icsneojavaJNI.neomessage_statusbitfield_t_ifrData_get(swigCPtr, this);
  }

  public void setHardwareCommError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_hardwareCommError_set(swigCPtr, this, value);
  }

  public long getHardwareCommError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_hardwareCommError_get(swigCPtr, this);
  }

  public void setExpectedLengthError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_expectedLengthError_set(swigCPtr, this, value);
  }

  public long getExpectedLengthError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_expectedLengthError_get(swigCPtr, this);
  }

  public void setIncomingNoMatch(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_incomingNoMatch_set(swigCPtr, this, value);
  }

  public long getIncomingNoMatch() {
    return icsneojavaJNI.neomessage_statusbitfield_t_incomingNoMatch_get(swigCPtr, this);
  }

  public void setStatusBreak(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_statusBreak_set(swigCPtr, this, value);
  }

  public long getStatusBreak() {
    return icsneojavaJNI.neomessage_statusbitfield_t_statusBreak_get(swigCPtr, this);
  }

  public void setAvsiRecOverflow(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_avsiRecOverflow_set(swigCPtr, this, value);
  }

  public long getAvsiRecOverflow() {
    return icsneojavaJNI.neomessage_statusbitfield_t_avsiRecOverflow_get(swigCPtr, this);
  }

  public void setTestTrigger(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_testTrigger_set(swigCPtr, this, value);
  }

  public long getTestTrigger() {
    return icsneojavaJNI.neomessage_statusbitfield_t_testTrigger_get(swigCPtr, this);
  }

  public void setAudioComment(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_audioComment_set(swigCPtr, this, value);
  }

  public long getAudioComment() {
    return icsneojavaJNI.neomessage_statusbitfield_t_audioComment_get(swigCPtr, this);
  }

  public void setGpsData(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_gpsData_set(swigCPtr, this, value);
  }

  public long getGpsData() {
    return icsneojavaJNI.neomessage_statusbitfield_t_gpsData_get(swigCPtr, this);
  }

  public void setAnalogDigitalInput(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_analogDigitalInput_set(swigCPtr, this, value);
  }

  public long getAnalogDigitalInput() {
    return icsneojavaJNI.neomessage_statusbitfield_t_analogDigitalInput_get(swigCPtr, this);
  }

  public void setTextComment(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_textComment_set(swigCPtr, this, value);
  }

  public long getTextComment() {
    return icsneojavaJNI.neomessage_statusbitfield_t_textComment_get(swigCPtr, this);
  }

  public void setNetworkMessageType(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_networkMessageType_set(swigCPtr, this, value);
  }

  public long getNetworkMessageType() {
    return icsneojavaJNI.neomessage_statusbitfield_t_networkMessageType_get(swigCPtr, this);
  }

  public void setVsiTXUnderrun(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_vsiTXUnderrun_set(swigCPtr, this, value);
  }

  public long getVsiTXUnderrun() {
    return icsneojavaJNI.neomessage_statusbitfield_t_vsiTXUnderrun_get(swigCPtr, this);
  }

  public void setVsiIFRCRCBit(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_vsiIFRCRCBit_set(swigCPtr, this, value);
  }

  public long getVsiIFRCRCBit() {
    return icsneojavaJNI.neomessage_statusbitfield_t_vsiIFRCRCBit_get(swigCPtr, this);
  }

  public void setInitMessage(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_initMessage_set(swigCPtr, this, value);
  }

  public long getInitMessage() {
    return icsneojavaJNI.neomessage_statusbitfield_t_initMessage_get(swigCPtr, this);
  }

  public void setFlexraySecondStartupFrame(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_flexraySecondStartupFrame_set(swigCPtr, this, value);
  }

  public long getFlexraySecondStartupFrame() {
    return icsneojavaJNI.neomessage_statusbitfield_t_flexraySecondStartupFrame_get(swigCPtr, this);
  }

  public void setExtended(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_extended_set(swigCPtr, this, value);
  }

  public long getExtended() {
    return icsneojavaJNI.neomessage_statusbitfield_t_extended_get(swigCPtr, this);
  }

  public void setHasValue(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_hasValue_set(swigCPtr, this, value);
  }

  public long getHasValue() {
    return icsneojavaJNI.neomessage_statusbitfield_t_hasValue_get(swigCPtr, this);
  }

  public void setValueIsBoolean(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_valueIsBoolean_set(swigCPtr, this, value);
  }

  public long getValueIsBoolean() {
    return icsneojavaJNI.neomessage_statusbitfield_t_valueIsBoolean_get(swigCPtr, this);
  }

  public void setHighVoltage(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_highVoltage_set(swigCPtr, this, value);
  }

  public long getHighVoltage() {
    return icsneojavaJNI.neomessage_statusbitfield_t_highVoltage_get(swigCPtr, this);
  }

  public void setLongMessage(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_longMessage_set(swigCPtr, this, value);
  }

  public long getLongMessage() {
    return icsneojavaJNI.neomessage_statusbitfield_t_longMessage_get(swigCPtr, this);
  }

  public void setGlobalChange(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_globalChange_set(swigCPtr, this, value);
  }

  public long getGlobalChange() {
    return icsneojavaJNI.neomessage_statusbitfield_t_globalChange_get(swigCPtr, this);
  }

  public void setErrorFrame(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_errorFrame_set(swigCPtr, this, value);
  }

  public long getErrorFrame() {
    return icsneojavaJNI.neomessage_statusbitfield_t_errorFrame_get(swigCPtr, this);
  }

  public void setEndOfLongMessage(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_endOfLongMessage_set(swigCPtr, this, value);
  }

  public long getEndOfLongMessage() {
    return icsneojavaJNI.neomessage_statusbitfield_t_endOfLongMessage_get(swigCPtr, this);
  }

  public void setLinErrorRXBreakNotZero(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXBreakNotZero_set(swigCPtr, this, value);
  }

  public long getLinErrorRXBreakNotZero() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXBreakNotZero_get(swigCPtr, this);
  }

  public void setLinErrorRXBreakTooShort(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXBreakTooShort_set(swigCPtr, this, value);
  }

  public long getLinErrorRXBreakTooShort() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXBreakTooShort_get(swigCPtr, this);
  }

  public void setLinErrorRXSyncNot55(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXSyncNot55_set(swigCPtr, this, value);
  }

  public long getLinErrorRXSyncNot55() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXSyncNot55_get(swigCPtr, this);
  }

  public void setLinErrorRXDataGreaterEight(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXDataGreaterEight_set(swigCPtr, this, value);
  }

  public long getLinErrorRXDataGreaterEight() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorRXDataGreaterEight_get(swigCPtr, this);
  }

  public void setLinErrorTXRXMismatch(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorTXRXMismatch_set(swigCPtr, this, value);
  }

  public long getLinErrorTXRXMismatch() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorTXRXMismatch_get(swigCPtr, this);
  }

  public void setLinErrorMessageIDParity(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linErrorMessageIDParity_set(swigCPtr, this, value);
  }

  public long getLinErrorMessageIDParity() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linErrorMessageIDParity_get(swigCPtr, this);
  }

  public void setLinSyncFrameError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linSyncFrameError_set(swigCPtr, this, value);
  }

  public long getLinSyncFrameError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linSyncFrameError_get(swigCPtr, this);
  }

  public void setLinIDFrameError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linIDFrameError_set(swigCPtr, this, value);
  }

  public long getLinIDFrameError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linIDFrameError_get(swigCPtr, this);
  }

  public void setLinSlaveByteError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linSlaveByteError_set(swigCPtr, this, value);
  }

  public long getLinSlaveByteError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linSlaveByteError_get(swigCPtr, this);
  }

  public void setRxTimeoutError(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_rxTimeoutError_set(swigCPtr, this, value);
  }

  public long getRxTimeoutError() {
    return icsneojavaJNI.neomessage_statusbitfield_t_rxTimeoutError_get(swigCPtr, this);
  }

  public void setLinNoSlaveData(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_linNoSlaveData_set(swigCPtr, this, value);
  }

  public long getLinNoSlaveData() {
    return icsneojavaJNI.neomessage_statusbitfield_t_linNoSlaveData_get(swigCPtr, this);
  }

  public void setCanfdESI(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canfdESI_set(swigCPtr, this, value);
  }

  public long getCanfdESI() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canfdESI_get(swigCPtr, this);
  }

  public void setCanfdIDE(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canfdIDE_set(swigCPtr, this, value);
  }

  public long getCanfdIDE() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canfdIDE_get(swigCPtr, this);
  }

  public void setCanfdRTR(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canfdRTR_set(swigCPtr, this, value);
  }

  public long getCanfdRTR() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canfdRTR_get(swigCPtr, this);
  }

  public void setCanfdFDF(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canfdFDF_set(swigCPtr, this, value);
  }

  public long getCanfdFDF() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canfdFDF_get(swigCPtr, this);
  }

  public void setCanfdBRS(long value) {
    icsneojavaJNI.neomessage_statusbitfield_t_canfdBRS_set(swigCPtr, this, value);
  }

  public long getCanfdBRS() {
    return icsneojavaJNI.neomessage_statusbitfield_t_canfdBRS_get(swigCPtr, this);
  }

  public void setStatusBitfield(long[] value) {
    icsneojavaJNI.neomessage_statusbitfield_t_statusBitfield_set(swigCPtr, this, value);
  }

  public long[] getStatusBitfield() {
    return icsneojavaJNI.neomessage_statusbitfield_t_statusBitfield_get(swigCPtr, this);
  }

  public neomessage_statusbitfield_t() {
    this(icsneojavaJNI.new_neomessage_statusbitfield_t(), true);
  }

}
